import sqlite3
import os
from datetime import datetime
from flask import Flask, render_template, request, jsonify, session, redirect, url_for

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', 'guia-dw-secret-key-change-in-production')

DB_PATH = os.path.join(os.path.dirname(__file__), 'visitas.db')


def init_db():
    conn = sqlite3.connect(DB_PATH)
    conn.execute('''CREATE TABLE IF NOT EXISTS visitas (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nombre TEXT NOT NULL,
        fecha TEXT NOT NULL
    )''')
    conn.commit()
    conn.close()


def registrar_visita(nombre):
    conn = sqlite3.connect(DB_PATH)
    conn.execute('INSERT INTO visitas (nombre, fecha) VALUES (?, ?)',
                 (nombre.strip(), datetime.now().isoformat()))
    conn.commit()
    conn.close()


def contar_visitas():
    conn = sqlite3.connect(DB_PATH)
    count = conn.execute('SELECT COUNT(*) FROM visitas').fetchone()[0]
    conn.close()
    return count


def obtener_visitas():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute('SELECT * FROM visitas ORDER BY fecha DESC').fetchall()
    conn.close()
    return [dict(r) for r in rows]


init_db()

ENGINES = {
    'mysql': {
        'name': 'MySQL',
        'package': 'mysql2',
        'port': 3306,
        'default_schema': 'CREATE DATABASE IF NOT EXISTS {db};\nUSE {db};'
    },
    'postgres': {
        'name': 'PostgreSQL',
        'package': 'pg',
        'port': 5432,
        'default_schema': 'CREATE DATABASE {db};\n\\c {db};'
    },
    'sqlserver': {
        'name': 'SQL Server',
        'package': 'tedious',
        'port': 1433,
        'default_schema': "CREATE DATABASE {db};\nUSE [{db}];"
    },
    'oracle': {
        'name': 'Oracle',
        'package': 'oracledb',
        'port': 1521,
        'default_schema': 'CREATE USER {db} IDENTIFIED BY password;\nGRANT CONNECT, RESOURCE TO {db};'
    },
    'sqlite': {
        'name': 'SQLite',
        'package': 'sqlite3',
        'port': None,
        'default_schema': '-- No requiere creación explícita de base de datos'
    }
}

TYPE_MAP = {
    'INTEGER': {'mysql': 'INT', 'postgres': 'INTEGER', 'sqlserver': 'INT', 'oracle': 'NUMBER(10)', 'sqlite': 'INTEGER'},
    'BIGINT': {'mysql': 'BIGINT', 'postgres': 'BIGINT', 'sqlserver': 'BIGINT', 'oracle': 'NUMBER(19)', 'sqlite': 'INTEGER'},
    'VARCHAR': {'mysql': 'VARCHAR({len})', 'postgres': 'VARCHAR({len})', 'sqlserver': 'VARCHAR({len})', 'oracle': 'VARCHAR2({len})', 'sqlite': 'TEXT'},
    'TEXT': {'mysql': 'TEXT', 'postgres': 'TEXT', 'sqlserver': 'TEXT', 'oracle': 'CLOB', 'sqlite': 'TEXT'},
    'DECIMAL': {'mysql': 'DECIMAL({len})', 'postgres': 'NUMERIC({len})', 'sqlserver': 'DECIMAL({len})', 'oracle': 'NUMBER({len})', 'sqlite': 'REAL'},
    'DATE': {'mysql': 'DATE', 'postgres': 'DATE', 'sqlserver': 'DATE', 'oracle': 'DATE', 'sqlite': 'TEXT'},
    'TIMESTAMP': {'mysql': 'DATETIME', 'postgres': 'TIMESTAMP', 'sqlserver': 'DATETIME2', 'oracle': 'TIMESTAMP', 'sqlite': 'TEXT'},
    'BOOLEAN': {'mysql': 'TINYINT(1)', 'postgres': 'BOOLEAN', 'sqlserver': 'BIT', 'oracle': 'NUMBER(1)', 'sqlite': 'INTEGER'}
}

SEQUELIZE_TYPE_MAP = {
    'INTEGER': 'DataTypes.INTEGER',
    'BIGINT': 'DataTypes.BIGINT',
    'VARCHAR': 'DataTypes.STRING({len})',
    'TEXT': 'DataTypes.TEXT',
    'DECIMAL': 'DataTypes.DECIMAL({len})',
    'DATE': 'DataTypes.DATEONLY',
    'TIMESTAMP': 'DataTypes.DATE',
    'BOOLEAN': 'DataTypes.BOOLEAN'
}


def pluralize(name):
    if name.endswith(('s', 'x', 'z', 'ch', 'sh')):
        return name + 'es'
    if name.endswith('y'):
        return name[:-1] + 'ies'
    return name + 's'


def generate_sql(entity, plural, fields, engine):
    lines = []
    lines.append(f'CREATE TABLE IF NOT EXISTS {plural} (')

    col_lines = []
    for f in fields:
        n = f['name']
        t = f['type']
        l = f.get('length', '')
        pk = f.get('pk', False)
        nn = f.get('notNull', False)
        uniq = f.get('unique', False)
        dflt = f.get('default', '')

        if engine == 'mysql' and pk and n == 'id':
            col_lines.append(f'  {n} INT AUTO_INCREMENT PRIMARY KEY')
            continue
        elif engine == 'postgres' and pk and n == 'id':
            col_lines.append(f'  {n} SERIAL PRIMARY KEY')
            continue
        elif engine == 'sqlserver' and pk and n == 'id':
            col_lines.append(f'  {n} INT IDENTITY(1,1) PRIMARY KEY')
            continue
        elif engine == 'oracle' and pk and n == 'id':
            col_lines.append(f'  {n} NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
            continue
        elif engine == 'sqlite' and pk and n == 'id':
            col_lines.append(f'  {n} INTEGER PRIMARY KEY AUTOINCREMENT')
            continue

        sql_type = TYPE_MAP.get(t, {}).get(engine, 'VARCHAR(255)')
        if l and '{len}' in sql_type:
            sql_type = sql_type.replace('{len}', l)
        elif '{len}' in sql_type:
            sql_type = sql_type.replace('{len}', '255')

        col = f'  {n} {sql_type}'

        if pk:
            col += ' PRIMARY KEY'
        if nn:
            col += ' NOT NULL'
        if uniq:
            col += ' UNIQUE'
        if dflt:
            if engine == 'sqlserver':
                col += f" DEFAULT {dflt}"
            elif engine == 'mysql':
                col += f" DEFAULT {dflt}"
            elif engine == 'postgres':
                col += f" DEFAULT {dflt}"
            else:
                col += f" DEFAULT {dflt}"

        col_lines.append(col)

    if not any(f.get('pk') for f in fields):
        col_lines.append(f'  id INT AUTO_INCREMENT PRIMARY KEY' if engine == 'mysql' else
                         f'  id SERIAL PRIMARY KEY' if engine == 'postgres' else
                         f'  id INT IDENTITY(1,1) PRIMARY KEY' if engine == 'sqlserver' else
                         f'  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' if engine == 'oracle' else
                         f'  id INTEGER PRIMARY KEY AUTOINCREMENT')

    col_lines.append(f'  created_at {engine_time_col(engine, "created")}')
    col_lines.append(f'  updated_at {engine_time_col(engine, "updated")}')

    lines.append(',\n'.join(col_lines))
    lines.append(');')
    return '\n'.join(lines)


def engine_time_col(engine, kind):
    if engine == 'mysql':
        c = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        if kind == 'updated':
            c += " ON UPDATE CURRENT_TIMESTAMP"
        return c
    elif engine == 'postgres':
        c = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        return c
    elif engine == 'sqlserver':
        c = "DATETIME2 DEFAULT GETDATE()"
        return c
    elif engine == 'oracle':
        c = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        return c
    elif engine == 'sqlite':
        c = "TEXT DEFAULT (datetime('now'))"
        return c


def generate_db_config(entity, engine):
    info = ENGINES[engine]
    if engine == 'mysql':
        return f'''const mysql = require('mysql2/promise');
require('dotenv').config();

const pool = mysql.createPool({{
  host: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'root',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || '{entity}',
  port: parseInt(process.env.DB_PORT) || {info['port']},
  waitForConnections: true,
  connectionLimit: 10,
  queueLimit: 0
}});

module.exports = pool;'''
    elif engine == 'postgres':
        return f'''const {{ Pool }} = require('pg');
require('dotenv').config();

const pool = new Pool({{
  host: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || '{entity}',
  port: parseInt(process.env.DB_PORT) || {info['port']},
  max: 10,
  idleTimeoutMillis: 30000
}});

module.exports = pool;'''
    elif engine == 'sqlserver':
        return f'''const sql = require('mssql');
require('dotenv').config();

const config = {{
  server: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'sa',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || '{entity}',
  port: parseInt(process.env.DB_PORT) || {info['port']},
  options: {{ encrypt: false, trustServerCertificate: true }}
}};

const poolPromise = sql.connect(config)
  .then(pool => {{ console.log('Conectado a SQL Server'); return pool; }})
  .catch(err => {{ console.error('Error SQL Server:', err); process.exit(1); }});

module.exports = {{ sql, poolPromise }};'''
    elif engine == 'oracle':
        return f'''const oracledb = require('oracledb');
require('dotenv').config();

async function getConnection() {{
  const connection = await oracledb.getConnection({{
    user: process.env.DB_USER || 'admin',
    password: process.env.DB_PASSWORD || '',
    connectionString: `${{process.env.DB_HOST || 'localhost'}}:${{process.env.DB_PORT || {info['port']}}}/${{process.env.DB_NAME || '{entity}'}}`
  }});
  return connection;
}}

module.exports = {{ getConnection }};'''
    elif engine == 'sqlite':
        return f'''const {{ Sequelize }} = require('sequelize');
require('dotenv').config();

const sequelize = new Sequelize({{
  dialect: 'sqlite',
  storage: process.env.DB_STORAGE || './database.sqlite',
  logging: process.env.NODE_ENV === 'development' ? console.log : false
}});

module.exports = sequelize;'''


def generate_model(entity, plural, capitalized, fields, engine):
    field_defs = []
    field_names = []
    for f in fields:
        n = f['name']
        if n == 'id':
            continue
        t = f['type']
        l = f.get('length', '')
        nn = f.get('notNull', False)
        dflt = f.get('default', '')

        st = SEQUELIZE_TYPE_MAP.get(t, 'DataTypes.STRING(255)')
        if l and '{len}' in st:
            st = st.replace('{len}', l)
        elif '{len}' in st:
            st = st.replace('{len}', '255')

        opts = [st]
        if nn:
            opts.append('allowNull: false')
        if dflt:
            opts.append(f'defaultValue: {dflt}')

        field_defs.append(f'    {n}: {{ {", ".join(opts)} }}')
        field_names.append(f"'{n}'")

    field_code = ',\n'.join(field_defs)
    field_list = ', '.join(field_names)

    if engine == 'sqlite':
        db_config = f'''const sequelize = new Sequelize({{
  dialect: 'sqlite',
  storage: process.env.DB_STORAGE || './database.sqlite',
  logging: process.env.NODE_ENV === 'development' ? console.log : false
}});'''
    else:
        if engine == 'mysql':
            dialect = "'mysql'"
            extra_opts = "logging: process.env.NODE_ENV === 'development' ? console.log : false"
        elif engine == 'postgres':
            dialect = "'postgres'"
            extra_opts = "logging: process.env.NODE_ENV === 'development' ? console.log : false"
        elif engine == 'sqlserver':
            dialect = "'mssql'"
            extra_opts = "logging: process.env.NODE_ENV === 'development' ? console.log : false, dialectOptions: { encrypt: false, trustServerCertificate: true }"
        elif engine == 'oracle':
            dialect = "'oracle'"
            extra_opts = "logging: process.env.NODE_ENV === 'development' ? console.log : false"

        db_config = f'''const sequelize = new Sequelize(
  process.env.DB_NAME || '{entity}',
  process.env.DB_USER || 'root',
  process.env.DB_PASSWORD || '',
  {{
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT) || {ENGINES[engine]['port']},
    dialect: {dialect},
    {extra_opts}
  }}
);'''

    return f'''const {{ DataTypes, Sequelize }} = require('sequelize');
require('dotenv').config();

{db_config}

const {capitalized} = sequelize.define('{capitalized}', {{
{field_code}
}}, {{
  tableName: '{plural}',
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at'
}});

module.exports = {capitalized};'''


def generate_controller(entity, capitalized):
    return f'''const {capitalized} = require('../models/{entity}.model');

const {capitalized}Controller = {{
  getAll: async (req, res) => {{
    try {{ const items = await {capitalized}.findAll(); res.json({{ data: items }}); }}
    catch (error) {{ res.status(500).json({{ error: 'Error al obtener registros', detalle: error.message }}); }}
  }},
  getById: async (req, res) => {{
    try {{ const {{ id }} = req.params; const item = await {capitalized}.findByPk(id);
      if (!item) return res.status(404).json({{ error: 'No encontrado' }}); res.json({{ data: item }}); }}
    catch (error) {{ res.status(500).json({{ error: 'Error al obtener' }}); }}
  }},
  create: async (req, res) => {{
    try {{ const newItem = await {capitalized}.create(req.body);
      res.status(201).json({{ data: newItem, mensaje: 'Creado correctamente' }}); }}
    catch (error) {{ res.status(500).json({{ error: 'Error al crear', detalle: error.message }}); }}
  }},
  update: async (req, res) => {{
    try {{ const {{ id }} = req.params; const item = await {capitalized}.findByPk(id);
      if (!item) return res.status(404).json({{ error: 'No encontrado' }});
      await item.update(req.body); res.json({{ data: item, mensaje: 'Actualizado correctamente' }}); }}
    catch (error) {{ res.status(500).json({{ error: 'Error al actualizar' }}); }}
  }},
  delete: async (req, res) => {{
    try {{ const {{ id }} = req.params; const item = await {capitalized}.findByPk(id);
      if (!item) return res.status(404).json({{ error: 'No encontrado' }});
      await item.destroy(); res.json({{ mensaje: 'Eliminado correctamente' }}); }}
    catch (error) {{ res.status(500).json({{ error: 'Error al eliminar' }}); }}
  }}
}};

module.exports = {capitalized}Controller;'''


@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        nombre = request.form.get('nombre', '').strip()
        if nombre:
            session['usuario'] = nombre
            registrar_visita(nombre)
            return redirect(url_for('guia'))
        return render_template('login.html', error='Ingresa tu nombre')
    if 'usuario' not in session:
        return render_template('login.html')
    return redirect(url_for('guia'))


@app.route('/guia')
def guia():
    if 'usuario' not in session:
        return redirect(url_for('index'))
    return render_template('index.html', usuario=session['usuario'])


@app.route('/admin', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'POST':
        clave = request.form.get('clave', '').strip()
        admin_pass = os.environ.get('ADMIN_KEY', 'admin123')
        if clave == admin_pass:
            session['admin'] = True
            return redirect(url_for('admin_panel'))
        return render_template('admin.html', error='Clave incorrecta')
    if session.get('admin'):
        return redirect(url_for('admin_panel'))
    return render_template('admin.html')


@app.route('/admin/panel')
def admin_panel():
    if not session.get('admin'):
        return redirect(url_for('admin_login'))
    visitas = obtener_visitas()
    return render_template('admin.html', visitas=visitas)


@app.route('/admin/logout')
def admin_logout():
    session.pop('admin', None)
    return redirect(url_for('admin_login'))


@app.route('/api/stats')
def api_stats():
    return jsonify({'total': contar_visitas()})


@app.route('/api/generate', methods=['POST'])
def generate_code():
    data = request.get_json()
    if not data:
        return jsonify({'error': 'Datos JSON requeridos'}), 400

    entity = data.get('entity', '').lower().strip()
    engine = data.get('engine', 'mysql')
    fields = data.get('fields', [])

    if not entity:
        return jsonify({'error': 'Nombre de entidad requerido'}), 400
    if engine not in ENGINES:
        return jsonify({'error': f'Motor no soportado: {engine}'}), 400

    plural = pluralize(entity)
    capitalized = entity.capitalize()

    sql = generate_sql(entity, plural, fields, engine)
    db_config = generate_db_config(entity, engine)
    model = generate_model(entity, plural, capitalized, fields, engine)
    controller = generate_controller(entity, capitalized)

    routes = f'''const router = require('express').Router();
const controller = require('../controllers/{entity}.controller');

router.get('/{plural}', controller.getAll);
router.get('/{plural}/:id', controller.getById);
router.post('/{plural}', controller.create);
router.put('/{plural}/:id', controller.update);
router.delete('/{plural}/:id', controller.delete);

module.exports = router;'''

    angular_fields = []
    ang_interfaces = []
    for f in fields:
        n = f['name']
        if n == 'id':
            ang_interfaces.append(f'  {n}?: number;')
            continue
        t = f['type']
        if t in ('INTEGER', 'BIGINT', 'DECIMAL'):
            ang_interfaces.append(f'  {n}: number;')
        elif t == 'BOOLEAN':
            ang_interfaces.append(f'  {n}: boolean;')
        else:
            ang_interfaces.append(f'  {n}: string;')

    angular_model = f'''export interface {capitalized} {{\n''' + '\n'.join(ang_interfaces) + '\n}'

    angular_service = f'''import {{ Injectable }} from '@angular/core';
import {{ HttpClient }} from '@angular/common/http';
import {{ Observable }} from 'rxjs';
import {{ {capitalized} }} from '../models/{entity}';

@Injectable({{ providedIn: 'root' }})
export class {capitalized}Service {{
  private apiUrl = 'http://localhost:3000/api/{plural}';

  constructor(private http: HttpClient) {{ }}

  getAll(): Observable<{{ data: {capitalized}[] }}> {{ return this.http.get<{{ data: {capitalized}[] }}>(this.apiUrl); }}
  getById(id: number): Observable<{{ data: {capitalized} }}> {{ return this.http.get<{{ data: {capitalized} }}>(`${{this.apiUrl}}/${{id}}`); }}
  create(data: {capitalized}): Observable<any> {{ return this.http.post(this.apiUrl, data); }}
  update(id: number, data: {capitalized}): Observable<any> {{ return this.http.put(`${{this.apiUrl}}/${{id}}`, data); }}
  delete(id: number, data: {capitalized}): Observable<any> {{ return this.http.delete(`${{this.apiUrl}}/${{id}}`); }}
}}'''

    seed = generate_seed(entity, capitalized, fields, engine)
    env_config = generate_env(entity, engine)
    deps = f'npm install express cors dotenv sequelize {ENGINES[engine]["package"]}\nnpm install -D nodemon'

    http_client = generate_http_client(entity, plural)

    return jsonify({
        'entity': entity,
        'entityCapitalized': capitalized,
        'plural': plural,
        'engine': engine,
        'engineName': ENGINES[engine]['name'],
        'dependencies': deps,
        'env': env_config,
        'sql': sql,
        'dbConfig': db_config,
        'model': model,
        'controller': controller,
        'routes': routes,
        'angularModel': angular_model,
        'angularService': angular_service,
        'seed': seed,
        'httpClient': http_client
    })


def generate_env(entity, engine):
    if engine == 'sqlite':
        return f'''PORT=3000
DB_STORAGE=./database.sqlite
JWT_SECRET=your_secret_key'''
    info = ENGINES[engine]
    return f'''PORT=3000
DB_HOST=localhost
DB_USER=root
DB_PASSWORD=
DB_NAME={entity}
DB_PORT={info['port']}
JWT_SECRET=your_secret_key'''


def generate_seed(entity, capitalized, fields, engine):
    field_assignments = []
    for f in fields:
        n = f['name']
        if n == 'id' or n == 'created_at' or n == 'updated_at':
            continue
        t = f['type']
        if t == 'VARCHAR':
            field_assignments.append(f'      {n}: faker.commerce.productName(),')
        elif t == 'TEXT':
            field_assignments.append(f'      {n}: faker.lorem.sentence(),')
        elif t in ('INTEGER', 'BIGINT'):
            field_assignments.append(f'      {n}: faker.number.int({{ min: 1, max: 100 }}),')
        elif t == 'DECIMAL':
            field_assignments.append(f'      {n}: parseFloat(faker.commerce.price()),')
        elif t == 'BOOLEAN':
            field_assignments.append(f'      {n}: faker.datatype.boolean(),')
        elif t in ('DATE', 'TIMESTAMP'):
            field_assignments.append(f'      {n}: faker.date.past(),')
        else:
            field_assignments.append(f'      {n}: faker.lorem.word(),')

    if not field_assignments:
        return '// Agrega campos a tu entidad para generar datos de prueba con faker'

    fa = '\n'.join(field_assignments)

    return f'''const {{ faker }} = require('@faker-js/faker');
const {capitalized} = require('../models/{entity}.model');

async function seed() {{
  console.log('Insertando datos de prueba...');
  for (let i = 0; i < 20; i++) {{
    await {capitalized}.create({{
{fa}
    }});
  }}
  console.log('Datos insertados correctamente');
  process.exit(0);
}}

seed().catch(err => {{ console.error(err); process.exit(1); }});'''


def generate_http_client(entity, plural):
    return f'''### LISTAR TODOS (GET)
GET http://localhost:3000/api/{plural}

### OBTENER POR ID (GET)
GET http://localhost:3000/api/{plural}/1

### CREAR (POST)
POST http://localhost:3000/api/{plural}
Content-Type: application/json

{{
  "nombre": "Ejemplo",
  "descripcion": "Descripción del registro"
}}

### ACTUALIZAR (PUT)
PUT http://localhost:3000/api/{plural}/1
Content-Type: application/json

{{
  "nombre": "Ejemplo Actualizado"
}}

### ELIMINAR (DELETE)
DELETE http://localhost:3000/api/{plural}/1
'''


@app.route('/api/engines')
def get_engines():
    return jsonify({k: {'name': v['name'], 'port': v['port'] if v['port'] else 0} for k, v in ENGINES.items()})


@app.route('/api/types')
def get_types():
    return jsonify(list(TYPE_MAP.keys()))


if __name__ == '__main__':
    import os
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)
