import sqlite3
import os
from datetime import datetime
from flask import Flask, render_template, request, jsonify, session, redirect, url_for
from whitenoise import WhiteNoise

app = Flask(__name__)
app.wsgi_app = WhiteNoise(app.wsgi_app, root=os.path.join(os.path.dirname(__file__), 'static'), prefix='static/')
app.secret_key = os.environ.get('SECRET_KEY', 'guia-dw-secret-key-change-in-production')

DB_PATH = os.path.join(os.path.dirname(__file__), 'visitas.db')


def init_db():
    conn = sqlite3.connect(DB_PATH)
    conn.execute('''CREATE TABLE IF NOT EXISTS visitas (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nombre TEXT NOT NULL,
        fecha TEXT NOT NULL
    )''')
    conn.commit()
    conn.close()


def registrar_visita(nombre):
    conn = sqlite3.connect(DB_PATH)
    conn.execute('INSERT INTO visitas (nombre, fecha) VALUES (?, ?)',
                 (nombre.strip(), datetime.now().isoformat()))
    conn.commit()
    conn.close()


def contar_visitas():
    conn = sqlite3.connect(DB_PATH)
    count = conn.execute('SELECT COUNT(*) FROM visitas').fetchone()[0]
    conn.close()
    return count


def obtener_visitas():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute('SELECT * FROM visitas ORDER BY fecha DESC').fetchall()
    conn.close()
    return [dict(r) for r in rows]


init_db()

ENGINES = {
    'mysql': {
        'name': 'MySQL',
        'package': 'mysql2',
        'port': 3306,
        'default_schema': 'CREATE DATABASE IF NOT EXISTS {db};\nUSE {db};'
    },
    'postgres': {
        'name': 'PostgreSQL',
        'package': 'pg',
        'port': 5432,
        'default_schema': 'CREATE DATABASE {db};\n\\c {db};'
    },
    'sqlserver': {
        'name': 'SQL Server',
        'package': 'tedious',
        'port': 1433,
        'default_schema': "CREATE DATABASE {db};\nUSE [{db}];"
    },
    'oracle': {
        'name': 'Oracle',
        'package': 'oracledb',
        'port': 1521,
        'default_schema': 'CREATE USER {db} IDENTIFIED BY password;\nGRANT CONNECT, RESOURCE TO {db};'
    },
    'sqlite': {
        'name': 'SQLite',
        'package': 'sqlite3',
        'port': None,
        'default_schema': '-- No requiere creación explícita de base de datos'
    }
}

TYPE_MAP = {
    'INTEGER': {'mysql': 'INT', 'postgres': 'INTEGER', 'sqlserver': 'INT', 'oracle': 'NUMBER(10)', 'sqlite': 'INTEGER'},
    'BIGINT': {'mysql': 'BIGINT', 'postgres': 'BIGINT', 'sqlserver': 'BIGINT', 'oracle': 'NUMBER(19)', 'sqlite': 'INTEGER'},
    'VARCHAR': {'mysql': 'VARCHAR({len})', 'postgres': 'VARCHAR({len})', 'sqlserver': 'VARCHAR({len})', 'oracle': 'VARCHAR2({len})', 'sqlite': 'TEXT'},
    'TEXT': {'mysql': 'TEXT', 'postgres': 'TEXT', 'sqlserver': 'TEXT', 'oracle': 'CLOB', 'sqlite': 'TEXT'},
    'DECIMAL': {'mysql': 'DECIMAL({len})', 'postgres': 'NUMERIC({len})', 'sqlserver': 'DECIMAL({len})', 'oracle': 'NUMBER({len})', 'sqlite': 'REAL'},
    'DATE': {'mysql': 'DATE', 'postgres': 'DATE', 'sqlserver': 'DATE', 'oracle': 'DATE', 'sqlite': 'TEXT'},
    'TIMESTAMP': {'mysql': 'DATETIME', 'postgres': 'TIMESTAMP', 'sqlserver': 'DATETIME2', 'oracle': 'TIMESTAMP', 'sqlite': 'TEXT'},
    'BOOLEAN': {'mysql': 'TINYINT(1)', 'postgres': 'BOOLEAN', 'sqlserver': 'BIT', 'oracle': 'NUMBER(1)', 'sqlite': 'INTEGER'}
}

def pluralize(name):
    if name.endswith(('s', 'x', 'z', 'ch', 'sh')):
        return name + 'es'
    if name.endswith('y'):
        return name[:-1] + 'ies'
    return name + 's'


def generate_sql(entity, plural, fields, engine):
    lines = []
    lines.append(f'CREATE TABLE IF NOT EXISTS {plural} (')

    col_lines = []
    for f in fields:
        n = f['name']
        t = f['type']
        l = f.get('length', '')
        pk = f.get('pk', False)
        nn = f.get('notNull', False)
        uniq = f.get('unique', False)
        dflt = f.get('default', '')

        if engine == 'mysql' and pk and n == 'id':
            col_lines.append(f'  {n} INT AUTO_INCREMENT PRIMARY KEY')
            continue
        elif engine == 'postgres' and pk and n == 'id':
            col_lines.append(f'  {n} SERIAL PRIMARY KEY')
            continue
        elif engine == 'sqlserver' and pk and n == 'id':
            col_lines.append(f'  {n} INT IDENTITY(1,1) PRIMARY KEY')
            continue
        elif engine == 'oracle' and pk and n == 'id':
            col_lines.append(f'  {n} NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
            continue
        elif engine == 'sqlite' and pk and n == 'id':
            col_lines.append(f'  {n} INTEGER PRIMARY KEY AUTOINCREMENT')
            continue

        sql_type = TYPE_MAP.get(t, {}).get(engine, 'VARCHAR(255)')
        if l and '{len}' in sql_type:
            sql_type = sql_type.replace('{len}', l)
        elif '{len}' in sql_type:
            sql_type = sql_type.replace('{len}', '255')

        col = f'  {n} {sql_type}'

        if pk:
            col += ' PRIMARY KEY'
        if nn:
            col += ' NOT NULL'
        if uniq:
            col += ' UNIQUE'
        if dflt:
            if engine == 'sqlserver':
                col += f" DEFAULT {dflt}"
            elif engine == 'mysql':
                col += f" DEFAULT {dflt}"
            elif engine == 'postgres':
                col += f" DEFAULT {dflt}"
            else:
                col += f" DEFAULT {dflt}"

        col_lines.append(col)

    if not any(f.get('pk') for f in fields):
        col_lines.append(f'  id INT AUTO_INCREMENT PRIMARY KEY' if engine == 'mysql' else
                         f'  id SERIAL PRIMARY KEY' if engine == 'postgres' else
                         f'  id INT IDENTITY(1,1) PRIMARY KEY' if engine == 'sqlserver' else
                         f'  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' if engine == 'oracle' else
                         f'  id INTEGER PRIMARY KEY AUTOINCREMENT')

    col_lines.append(f'  created_at {engine_time_col(engine, "created")}')
    col_lines.append(f'  updated_at {engine_time_col(engine, "updated")}')

    lines.append(',\n'.join(col_lines))
    lines.append(');')
    return '\n'.join(lines)


def engine_time_col(engine, kind):
    if engine == 'mysql':
        c = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        if kind == 'updated':
            c += " ON UPDATE CURRENT_TIMESTAMP"
        return c
    elif engine == 'postgres':
        c = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        return c
    elif engine == 'sqlserver':
        c = "DATETIME2 DEFAULT GETDATE()"
        return c
    elif engine == 'oracle':
        c = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
        return c
    elif engine == 'sqlite':
        c = "TEXT DEFAULT (datetime('now'))"
        return c


def generate_db_config(entity, engine):
    info = ENGINES[engine]
    if engine == 'mysql':
        return f'''const mysql = require('mysql2/promise');
require('dotenv').config();

const pool = mysql.createPool({{
  host: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'root',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || '{entity}',
  port: parseInt(process.env.DB_PORT) || {info['port']},
  waitForConnections: true,
  connectionLimit: 10,
  queueLimit: 0
}});

module.exports = pool;'''
    elif engine == 'postgres':
        return f'''const {{ Pool }} = require('pg');
require('dotenv').config();

const pool = new Pool({{
  host: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || '{entity}',
  port: parseInt(process.env.DB_PORT) || {info['port']},
  max: 10,
  idleTimeoutMillis: 30000
}});

module.exports = pool;'''
    elif engine == 'sqlserver':
        return f'''const sql = require('mssql');
require('dotenv').config();

const config = {{
  server: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'sa',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || '{entity}',
  port: parseInt(process.env.DB_PORT) || {info['port']},
  options: {{ encrypt: false, trustServerCertificate: true }}
}};

const poolPromise = sql.connect(config)
  .then(pool => {{ console.log('Conectado a SQL Server'); return pool; }})
  .catch(err => {{ console.error('Error SQL Server:', err); process.exit(1); }});

module.exports = {{ sql, poolPromise }};'''
    elif engine == 'oracle':
        return f'''const oracledb = require('oracledb');
require('dotenv').config();

async function getConnection() {{
  const connection = await oracledb.getConnection({{
    user: process.env.DB_USER || 'admin',
    password: process.env.DB_PASSWORD || '',
    connectionString: `${{process.env.DB_HOST || 'localhost'}}:${{process.env.DB_PORT || {info['port']}}}/${{process.env.DB_NAME || '{entity}'}}`
  }});
  return connection;
}}

module.exports = {{ getConnection }};'''
    elif engine == 'sqlite':
        return f'''const {{ Sequelize }} = require('sequelize');
require('dotenv').config();

const sequelize = new Sequelize({{
  dialect: 'sqlite',
  storage: process.env.DB_STORAGE || './database.sqlite',
  logging: process.env.NODE_ENV === 'development' ? console.log : false
}});

module.exports = sequelize;'''


def generate_model(entity, plural, capitalized, fields, engine):
    allowed = []
    for f in fields:
        n = f['name']
        if n == 'id':
            continue
        allowed.append(f"'{n}'")

    allowed_str = ', '.join(allowed)

    return f'''const pool = require('../config/db');

const tableName = '{plural}';
const allowedFields = [{allowed_str}];

const {capitalized}Model = {{
  getAll: async () => {{
    const [rows] = await pool.query(`SELECT * FROM ${{tableName}}`);
    return rows;
  }},

  getById: async (id) => {{
    const [rows] = await pool.query(`SELECT * FROM ${{tableName}} WHERE id = ?`, [id]);
    return rows[0];
  }},

  create: async (data) => {{
    const [result] = await pool.query(`INSERT INTO ${{tableName}} SET ?`, [data]);
    return {{ id: result.insertId, ...data }};
  }},

  update: async (id, data) => {{
    await pool.query(`UPDATE ${{tableName}} SET ? WHERE id = ?`, [data, id]);
    return {{ id, ...data }};
  }},

  delete: async (id) => {{
    const [result] = await pool.query(`DELETE FROM ${{tableName}} WHERE id = ?`, [id]);
    return result.affectedRows > 0;
  }}
}};

module.exports = {capitalized}Model;'''


def generate_controller(entity, capitalized, fields):
    field_names = []
    required_checks = []
    create_obj_fields = []
    for f in fields:
        n = f['name']
        if n == 'id':
            continue
        field_names.append(n)
        create_obj_fields.append(n)
        if f.get('notNull', False):
            required_checks.append(f"if (!{n}) {{\n        return res.status(400).json({{ error: '{n.capitalize()} es obligatorio' }});\n      }}")

    fields_destructure = ', '.join(field_names)
    create_obj = ', '.join(create_obj_fields)
    required_block = '\n      '.join(required_checks) if required_checks else ''

    return f'''const {capitalized}Model = require('../models/{entity}.model');

const {capitalized}Controller = {{
  getAll: async (req, res) => {{
    try {{
      const items = await {capitalized}Model.getAll();
      res.json({{ data: items }});
    }} catch (error) {{
      res.status(500).json({{ error: 'Error al obtener registros' }});
    }}
  }},

  getById: async (req, res) => {{
    try {{
      const {{ id }} = req.params;
      const item = await {capitalized}Model.getById(id);
      if (!item) return res.status(404).json({{ error: 'No encontrado' }});
      res.json({{ data: item }});
    }} catch (error) {{
      res.status(500).json({{ error: 'Error al obtener' }});
    }}
  }},

  create: async (req, res) => {{
    try {{
      const {{ {fields_destructure} }} = req.body;
      {required_block}
      const newItem = await {capitalized}Model.create({{ {create_obj} }});
      res.status(201).json({{ data: newItem, mensaje: 'Creado correctamente' }});
    }} catch (error) {{
      res.status(500).json({{ error: 'Error al crear' }});
    }}
  }},

  update: async (req, res) => {{
    try {{
      const {{ id }} = req.params;
      const item = await {capitalized}Model.getById(id);
      if (!item) return res.status(404).json({{ error: 'No encontrado' }});
      await {capitalized}Model.update(id, req.body);
      res.json({{ mensaje: 'Actualizado correctamente' }});
    }} catch (error) {{
      res.status(500).json({{ error: 'Error al actualizar' }});
    }}
  }},

  delete: async (req, res) => {{
    try {{
      const {{ id }} = req.params;
      const eliminado = await {capitalized}Model.delete(id);
      if (!eliminado) return res.status(404).json({{ error: 'No encontrado' }});
      res.json({{ mensaje: 'Eliminado correctamente' }});
    }} catch (error) {{
      res.status(500).json({{ error: 'Error al eliminar' }});
    }}
  }}
}};

module.exports = {capitalized}Controller;'''


def generate_angular_model(entity, capitalized, fields):
    interfaces = []
    for f in fields:
        n = f['name']
        if n == 'id':
            interfaces.append(f'  {n}?: number;')
            continue
        t = f['type']
        if t in ('INTEGER', 'BIGINT', 'DECIMAL'):
            interfaces.append(f'  {n}: number;')
        elif t == 'BOOLEAN':
            interfaces.append(f'  {n}: boolean;')
        else:
            interfaces.append(f'  {n}: string;')
    return f'export interface {capitalized} {{\n' + '\n'.join(interfaces) + '\n}'


def generate_angular_app_routes(entity, capitalized, plural):
    return f'''import {{ Routes }} from '@angular/router';

export const routes: Routes = [
  {{ path: '', redirectTo: '/{plural}', pathMatch: 'full' }},
  {{
    path: '{plural}',
    loadChildren: () => import('./components/{entity}/{entity}.routes').then(m => m.routes)
  }},
  {{ path: '**', redirectTo: '/{plural}' }}
];'''


def generate_angular_component_routes(entity, capitalized):
    return f'''import {{ Routes }} from '@angular/router';
import {{ {capitalized}List }} from './{entity}-list/{entity}-list';
import {{ {capitalized}Form }} from './{entity}-form/{entity}-form';

export const routes: Routes = [
  {{ path: '', component: {capitalized}List }},
  {{ path: 'new', component: {capitalized}Form }},
  {{ path: 'edit/:id', component: {capitalized}Form }}
];'''


def generate_angular_list_component(entity, capitalized, fields):
    confirm_field = ''
    for f in fields:
        if f['name'] != 'id':
            confirm_field = f['name']
            break

    return f'''import {{ Component, OnInit }} from '@angular/core';
import {{ CommonModule }} from '@angular/common';
import {{ RouterModule }} from '@angular/router';
import {{ TableModule }} from 'primeng/table';
import {{ ButtonModule }} from 'primeng/button';
import {{ ConfirmDialogModule }} from 'primeng/confirmdialog';
import {{ ToastModule }} from 'primeng/toast';
import {{ ConfirmationService, MessageService }} from 'primeng/api';
import {{ {capitalized}Service }} from '../../services/{entity}.service';
import {{ {capitalized} }} from '../../models/{entity}';

@Component({{
  selector: 'app-{entity}-list',
  standalone: true,
  imports: [CommonModule, RouterModule, TableModule, ButtonModule, ConfirmDialogModule, ToastModule],
  providers: [ConfirmationService, MessageService],
  templateUrl: './{entity}-list.html'
}})
export class {capitalized}List implements OnInit {{
  items: {capitalized}[] = [];
  loading = false;

  constructor(
    private service: {capitalized}Service,
    private confirmationService: ConfirmationService,
    private messageService: MessageService
  ) {{}}

  ngOnInit(): void {{ this.load(); }}

  load(): void {{
    this.loading = true;
    this.service.getAll().subscribe({{
      next: (res) => {{ this.items = res.data; this.loading = false; }},
      error: () => {{ this.loading = false; }}
    }});
  }}

  confirmDelete(item: {capitalized}): void {{
    this.confirmationService.confirm({{
      message: `¿Eliminar "${{item.{confirm_field}}}"?`,
      header: 'Confirmar',
      acceptLabel: 'Eliminar',
      rejectLabel: 'Cancelar',
      acceptButtonStyleClass: 'p-button-danger',
      accept: () => this.delete(item.id!)
    }});
  }}

  delete(id: number): void {{
    this.service.delete(id).subscribe({{
      next: () => {{ this.load(); this.messageService.add({{ severity: 'success', summary: 'Eliminado' }}); }},
      error: () => this.messageService.add({{ severity: 'error', summary: 'Error' }})
    }});
  }}
}}'''


def generate_angular_list_template(entity, capitalized, fields):
    non_id = [f for f in fields if f['name'] != 'id']
    header_cells = '\n'.join(
        f'        <th pSortableColumn="{f["name"]}">{f["name"].capitalize()} <p-sortIcon field="{f["name"]}"></p-sortIcon></th>'
        for f in non_id
    )
    body_cells = '\n'.join(
        f'        <td>{{{{ item.{f["name"]} }}}}</td>'
        for f in non_id
    )
    colspan = len(non_id) + 2

    return f'''<div class="card p-6">
  <div class="flex justify-between items-center mb-4">
    <h2 class="text-2xl font-bold">Listado de {capitalized}s</h2>
    <p-button label="Nuevo" icon="pi pi-plus" routerLink="/{entity}/new"></p-button>
  </div>

  <p-table [value]="items" [loading]="loading" [paginator]="true" [rows]="10"
    [rowsPerPageOptions]="[5,10,25,50]" dataKey="id" [tableStyle]={{{{'min-width':'50rem'}}}}>
    <ng-template pTemplate="header">
      <tr>
        <th pSortableColumn="id">ID <p-sortIcon field="id"></p-sortIcon></th>
{header_cells}
        <th class="text-center">Acciones</th>
      </tr>
    </ng-template>
    <ng-template pTemplate="body" let-item>
      <tr>
        <td>{{{{ item.id }}}}</td>
{body_cells}
        <td class="text-center">
          <p-button icon="pi pi-pencil" [routerLink]="['/{entity}/edit', item.id]"
            styleClass="p-button-rounded p-button-text p-button-warning" pTooltip="Editar"></p-button>
          <p-button icon="pi pi-trash" (onClick)="confirmDelete(item)"
            styleClass="p-button-rounded p-button-text p-button-danger" pTooltip="Eliminar"></p-button>
        </td>
      </tr>
    </ng-template>
    <ng-template pTemplate="emptymessage">
      <tr><td colspan="{colspan}" class="text-center p-4">No hay registros</td></tr>
    </ng-template>
  </p-table>
</div>
<p-confirmDialog></p-confirmDialog>
<p-toast></p-toast>'''


def generate_angular_form_component(entity, capitalized, fields):
    control_lines = []
    for f in fields:
        n = f['name']
        if n == 'id':
            continue
        nn = f.get('notNull', False)
        t = f['type']
        validators = []
        if nn:
            validators.append('Validators.required')
        if t in ('INTEGER', 'BIGINT', 'DECIMAL'):
            if t in ('INTEGER', 'BIGINT'):
                validators.append('Validators.min(0)')
            else:
                validators.append('Validators.min(1)')
            v = ', '.join(validators)
            if v:
                control_lines.append(f"    {n}: [0, [{v}]]")
            else:
                control_lines.append(f"    {n}: [0]")
        else:
            if t == 'VARCHAR':
                validators.append('Validators.minLength(2)')
            v = ', '.join(validators)
            if v:
                control_lines.append(f"    {n}: ['', [{v}]]")
            else:
                control_lines.append(f"    {n}: ['']")

    controls = ',\n'.join(control_lines)

    return f'''import {{ Component, OnInit }} from '@angular/core';
import {{ CommonModule }} from '@angular/common';
import {{ FormBuilder, ReactiveFormsModule, Validators }} from '@angular/forms';
import {{ ActivatedRoute, Router, RouterModule }} from '@angular/router';
import {{ ButtonModule }} from 'primeng/button';
import {{ InputTextModule }} from 'primeng/inputtext';
import {{ InputNumberModule }} from 'primeng/inputnumber';
import {{ SelectModule }} from 'primeng/select';
import {{ ToastModule }} from 'primeng/toast';
import {{ MessageService }} from 'primeng/api';
import {{ {capitalized}Service }} from '../../services/{entity}.service';

@Component({{
  selector: 'app-{entity}-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule, ButtonModule,
    InputTextModule, InputNumberModule, SelectModule, ToastModule],
  providers: [MessageService],
  templateUrl: './{entity}-form.html'
}})
export class {capitalized}Form implements OnInit {{
  form = this.fb.group({{
{controls}
  }});

  isEdit = false;
  id?: number;
  loading = false;

  constructor(
    private fb: FormBuilder,
    private service: {capitalized}Service,
    private route: ActivatedRoute,
    private router: Router,
    private messageService: MessageService
  ) {{}}

  ngOnInit(): void {{
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {{ this.isEdit = true; this.id = +idParam; this.loadItem(); }}
  }}

  loadItem(): void {{
    this.service.getById(this.id!).subscribe({{
      next: (res) => this.form.patchValue(res.data)
    }});
  }}

  submit(): void {{
    if (this.form.invalid) return;
    this.loading = true;
    const obs = this.isEdit
      ? this.service.update(this.id!, this.form.value as any)
      : this.service.create(this.form.value as any);
    obs.subscribe({{
      next: () => {{
        this.messageService.add({{ severity: 'success', summary: 'Éxito',
          detail: `Registro ${{this.isEdit ? 'actualizado' : 'creado'}} correctamente` }});
        setTimeout(() => this.router.navigate(['/{entity}']), 1000);
      }},
      error: () => {{ this.loading = false; }}
    }});
  }}

  cancel(): void {{ this.router.navigate(['/{entity}']); }}
}}'''


def generate_angular_form_template(entity, capitalized, fields):
    field_groups = []
    non_id = [f for f in fields if f['name'] != 'id']
    half = (len(non_id) + 1) // 2

    def input_html(f):
        n = f['name']
        t = f['type']
        label = n.capitalize()
        required = f.get('notNull', False)
        asterisk = ' *' if required else ''
        required_class = ' required' if required else ''

        if t in ('INTEGER', 'BIGINT', 'DECIMAL'):
            return f'''        <div>
            <label class="block font-semibold mb-1{required_class}">{label}{asterisk}</label>
            <p-inputNumber formControlName="{n}" [min]="0" class="w-full" />
          </div>'''
        else:
            return f'''        <div>
            <label class="block font-semibold mb-1{required_class}">{label}{asterisk}</label>
            <input pInputText formControlName="{n}" class="w-full" />
          </div>'''

    inputs = '\n'.join(input_html(f) for f in non_id)

    return f'''<div class="max-w-2xl mx-auto p-6">
  <div class="bg-white rounded-lg shadow-lg p-8">
    <h2 class="text-2xl font-bold mb-6">{{{{ isEdit ? 'Editar' : 'Nuevo' }}}} {capitalized}</h2>
    <form [formGroup]="form" (ngSubmit)="submit()">
      <div class="flex flex-col gap-4">
{inputs}
      </div>
      <div class="flex justify-center gap-4 mt-8">
        <p-button type="submit" label="Guardar" icon="pi pi-save" [loading]="loading" [disabled]="form.invalid"></p-button>
        <p-button type="button" label="Cancelar" icon="pi pi-times" severity="secondary" (onClick)="cancel()"></p-button>
      </div>
    </form>
  </div>
</div>
<p-toast></p-toast>'''


@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        nombre = request.form.get('nombre', '').strip()
        if nombre:
            session['usuario'] = nombre
            registrar_visita(nombre)
            return redirect(url_for('guia'))
        return render_template('login.html', error='Ingresa tu nombre')
    if 'usuario' not in session:
        return render_template('login.html')
    return redirect(url_for('guia'))


@app.route('/guia')
def guia():
    if 'usuario' not in session:
        return redirect(url_for('index'))
    return render_template('index.html', usuario=session['usuario'])


@app.route('/admin', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'POST':
        clave = request.form.get('clave', '').strip()
        admin_pass = os.environ.get('ADMIN_KEY', 'admin123')
        if clave == admin_pass:
            session['admin'] = True
            return redirect(url_for('admin_panel'))
        return render_template('admin.html', error='Clave incorrecta')
    if session.get('admin'):
        return redirect(url_for('admin_panel'))
    return render_template('admin.html')


@app.route('/admin/panel')
def admin_panel():
    if not session.get('admin'):
        return redirect(url_for('admin_login'))
    visitas = obtener_visitas()
    return render_template('admin.html', visitas=visitas)


@app.route('/admin/logout')
def admin_logout():
    session.pop('admin', None)
    return redirect(url_for('admin_login'))


@app.route('/api/stats')
def api_stats():
    return jsonify({'total': contar_visitas()})


@app.route('/api/generate', methods=['POST'])
def generate_code():
    data = request.get_json()
    if not data:
        return jsonify({'error': 'Datos JSON requeridos'}), 400

    entity = data.get('entity', '').lower().strip()
    engine = data.get('engine', 'mysql')
    fields = data.get('fields', [])

    if not entity:
        return jsonify({'error': 'Nombre de entidad requerido'}), 400
    if engine not in ENGINES:
        return jsonify({'error': f'Motor no soportado: {engine}'}), 400

    plural = pluralize(entity)
    capitalized = entity.capitalize()

    sql = generate_sql(entity, plural, fields, engine)
    db_config = generate_db_config(entity, engine)
    model = generate_model(entity, plural, capitalized, fields, engine)
    controller = generate_controller(entity, capitalized, fields)

    routes = f'''const router = require('express').Router();
const controller = require('../controllers/{entity}.controller');

router.get('/{plural}', controller.getAll);
router.get('/{plural}/:id', controller.getById);
router.post('/{plural}', controller.create);
router.put('/{plural}/:id', controller.update);
router.delete('/{plural}/:id', controller.delete);

module.exports = router;'''

    angular_model = generate_angular_model(entity, capitalized, fields)

    angular_service = f'''import {{ Injectable }} from '@angular/core';
import {{ HttpClient }} from '@angular/common/http';
import {{ Observable }} from 'rxjs';
import {{ {capitalized} }} from '../models/{entity}';

@Injectable({{ providedIn: 'root' }})
export class {capitalized}Service {{
  private apiUrl = 'http://localhost:3000/api/{plural}';

  constructor(private http: HttpClient) {{ }}

  getAll(): Observable<{{ data: {capitalized}[] }}> {{ return this.http.get<{{ data: {capitalized}[] }}>(this.apiUrl); }}
  getById(id: number): Observable<{{ data: {capitalized} }}> {{ return this.http.get<{{ data: {capitalized} }}>(`${{this.apiUrl}}/${{id}}`); }}
  create(data: {capitalized}): Observable<any> {{ return this.http.post(this.apiUrl, data); }}
  update(id: number, data: {capitalized}): Observable<any> {{ return this.http.put(`${{this.apiUrl}}/${{id}}`, data); }}
  delete(id: number): Observable<any> {{ return this.http.delete(`${{this.apiUrl}}/${{id}}`); }}
}}'''

    angular_app_routes = generate_angular_app_routes(entity, capitalized, plural)
    angular_component_routes = generate_angular_component_routes(entity, capitalized)
    angular_list_component = generate_angular_list_component(entity, capitalized, fields)
    angular_list_template = generate_angular_list_template(entity, capitalized, fields)
    angular_form_component = generate_angular_form_component(entity, capitalized, fields)
    angular_form_template = generate_angular_form_template(entity, capitalized, fields)

    seed = generate_seed(entity, capitalized, fields, engine)
    env_config = generate_env(entity, engine)
    deps = f'npm install express cors dotenv sequelize {ENGINES[engine]["package"]}\nnpm install -D nodemon'

    http_client = generate_http_client(entity, plural)

    return jsonify({
        'entity': entity,
        'entityCapitalized': capitalized,
        'plural': plural,
        'engine': engine,
        'engineName': ENGINES[engine]['name'],
        'dependencies': deps,
        'env': env_config,
        'sql': sql,
        'dbConfig': db_config,
        'model': model,
        'controller': controller,
        'routes': routes,
        'angularModel': angular_model,
        'angularService': angular_service,
        'angularAppRoutes': angular_app_routes,
        'angularComponentRoutes': angular_component_routes,
        'angularListComponent': angular_list_component,
        'angularListTemplate': angular_list_template,
        'angularFormComponent': angular_form_component,
        'angularFormTemplate': angular_form_template,
        'seed': seed,
        'httpClient': http_client
    })


def generate_env(entity, engine):
    if engine == 'sqlite':
        return f'''PORT=3000
DB_STORAGE=./database.sqlite
JWT_SECRET=your_secret_key'''
    info = ENGINES[engine]
    return f'''PORT=3000
DB_HOST=localhost
DB_USER=root
DB_PASSWORD=
DB_NAME={entity}
DB_PORT={info['port']}
JWT_SECRET=your_secret_key'''


def generate_seed(entity, capitalized, fields, engine):
    field_assignments = []
    for f in fields:
        n = f['name']
        if n == 'id' or n == 'created_at' or n == 'updated_at':
            continue
        t = f['type']
        if t == 'VARCHAR':
            field_assignments.append(f'      {n}: faker.commerce.productName(),')
        elif t == 'TEXT':
            field_assignments.append(f'      {n}: faker.lorem.sentence(),')
        elif t in ('INTEGER', 'BIGINT'):
            field_assignments.append(f'      {n}: faker.number.int({{ min: 1, max: 100 }}),')
        elif t == 'DECIMAL':
            field_assignments.append(f'      {n}: parseFloat(faker.commerce.price()),')
        elif t == 'BOOLEAN':
            field_assignments.append(f'      {n}: faker.datatype.boolean(),')
        elif t in ('DATE', 'TIMESTAMP'):
            field_assignments.append(f'      {n}: faker.date.past(),')
        else:
            field_assignments.append(f'      {n}: faker.lorem.word(),')

    if not field_assignments:
        return '// Agrega campos a tu entidad para generar datos de prueba con faker'

    fa = '\n'.join(field_assignments)

    return f'''const {{ faker }} = require('@faker-js/faker');
const {capitalized} = require('../models/{entity}.model');

async function seed() {{
  console.log('Insertando datos de prueba...');
  for (let i = 0; i < 20; i++) {{
    await {capitalized}.create({{
{fa}
    }});
  }}
  console.log('Datos insertados correctamente');
  process.exit(0);
}}

seed().catch(err => {{ console.error(err); process.exit(1); }});'''


def generate_http_client(entity, plural):
    return f'''### LISTAR TODOS (GET)
GET http://localhost:3000/api/{plural}

### OBTENER POR ID (GET)
GET http://localhost:3000/api/{plural}/1

### CREAR (POST)
POST http://localhost:3000/api/{plural}
Content-Type: application/json

{{
  "nombre": "Ejemplo",
  "descripcion": "Descripción del registro"
}}

### ACTUALIZAR (PUT)
PUT http://localhost:3000/api/{plural}/1
Content-Type: application/json

{{
  "nombre": "Ejemplo Actualizado"
}}

### ELIMINAR (DELETE)
DELETE http://localhost:3000/api/{plural}/1
'''


@app.route('/api/engines')
def get_engines():
    return jsonify({k: {'name': v['name'], 'port': v['port'] if v['port'] else 0} for k, v in ENGINES.items()})


@app.route('/api/types')
def get_types():
    return jsonify(list(TYPE_MAP.keys()))


if __name__ == '__main__':
    import os
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)

